Requires naemon-tools to install
Got error without naemon-tools:

```
Error: Package: naemon-1.0.3-1.el6.x86_64 (/naemon-1.0.3-1.rhel6.x86_64)
           Requires: naemon-tools = 1.0.3-1.el6
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest
```